### ISSUE TITLE
Bug in v0.1.3

### ISSUE THREAD

**Issue by Exelord** [pzuraq/ember-classic-decorator#10]
After upgrade to v0.1.3 I got following issue:

```
window.__CLASSIC_HAS_CONSTRUCTOR__.add is not a function

 at Module.callback (http://localhost:7357/assets/vendor.js:109084:38)
    at Module.exports (http://localhost:7357/assets/vendor.js:111:32)
    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)
    at Module.reify (http://localhost:7357/assets/vendor.js:135:27)
    at Module.exports (http://localhost:7357/assets/vendor.js:109:10)
    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)
    at Module.reify (http://localhost:7357/assets/vendor.js:135:27)
    at Module.exports (http://localhost:7357/assets/vendor.js:109:10)
    at Module._reify (http://localhost:7357/assets/vendor.js:148:59)
    at Module.reify (http://localhost:7357/assets/vendor.js:135:27)
```

**Comment by Exelord** [comment]
Sorry, works after reinstalling node_modules
